apiVersion: v2
name: activemq
description: A Helm chart for ActiveMQ

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.1

keywords:
  - activemq
home: https://activemq.apache.org/
icon: https://activemq.apache.org/assets/img/activemq_logo_black_small.png
sources:
  - https://www.github.com/rmohr/docker-activemq
maintainers:
  - name: Bruno Jost
    email: bruno.jost@bedag.ch
  - name: SRE
    email: sre@bedag.ch

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 5.11.1
dependencies:
 - name: manifests
   version: "0.5.1"
   repository: file://./charts/manifests
